// example/angular-app/src/app/app.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, type ElementRef, ViewChild } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { loadDialogWidget, loadFormWidget } from 'polkadot-sufficient-assets';
import { libConfig, libTheme } from '../lib/lib-config';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class AppComponent {
  title = 'angular-app';
  appConfig = libConfig;
  appTheme = libTheme;

  @ViewChild('psaDialog', { static: false }) psaDialog!: ElementRef;

  constructor() {
    loadFormWidget();
    loadDialogWidget();
  }

  handleClose() {
    this.psaDialog.nativeElement.open = false;
  }
  handleOpen() {
    this.psaDialog.nativeElement.open = true;
  }
}

<main class="main">
  <psa-dialog
    #psaDialog
    [config]="appConfig"
    [theme]="appTheme"
    [handleClose]="handleClose.bind(this)"
  />

  <button (click)="handleOpen()">Open Dialog</button>
  <div
    style="
      max-width: 450px;
      margin: 0 auto;
      min-height: 100dvh;
      display: flex;
      align-items: center;
      justify-content: center;
      width: 100%;
    "
  >
    <div style="width: 100%">
      <psa-form [config]="appConfig" [theme]="appTheme" />
    </div>
  </div>
</main>

<router-outlet />

// example/vue-app/src/App.vue
<template>
  <!-- Reference the dialog component with ref -->
  <psa-dialog
    v-if="dialogWidgetLoaded"
    :config.prop="libConfig"
    :theme.prop="appTheme"
    :open.prop="open"
    :handleClose.prop="closeDialog"
  />
  <button @click="openDialog">Open Dialog</button>

  <div
    style="
      max-width: 450px;
      margin: 0 auto;
      min-height: 100dvh;
      display: flex;
      align-items: center;
      justify-content: center;
      width: 100%;
    "
  >
    <div style="width: 100%">
      <psa-form
        v-if="formWidgetLoaded"
        :config.prop="libConfig"
        :theme.prop="appTheme"
      />
    </div>
  </div>
</template>

<script lang="ts">
import { loadDialogWidget, loadFormWidget } from "polkadot-sufficient-assets";
import { defineComponent, onMounted, ref } from "vue";
import { libConfig, libTheme } from "./lib/lib-config";

export default defineComponent({
  name: "App",
  setup() {
    // Define TypeScript types for the refs
    const formWidgetLoaded = ref(false); // Track if the form widget is loaded
    const dialogWidgetLoaded = ref(false); // Track if the form widget is loaded

    const appConfig = ref(libConfig);
    const appTheme = ref(libTheme);

    const open = ref(false);

    // Lifecycle hook: onMounted is similar to Angular's ngAfterViewInit
    onMounted(async () => {
      await loadFormWidget().then(() => {
        formWidgetLoaded.value = true;
      });

      await loadDialogWidget().then(() => {
        dialogWidgetLoaded.value = true;
      });
    });

    const openDialog = () => {
      open.value = true;
    };
    const closeDialog = () => {
      open.value = false;
    };

    return {
      libConfig,
      appConfig,
      appTheme,
      formWidgetLoaded,
      dialogWidgetLoaded,
      openDialog,
      closeDialog,
      open,
    };
  },
});
</script>
